version: "3.9"

services:
  warp-unlimited:
    image: ghcr.io/thecaduceus/warp-unlimited-docker:okteto
    container_name: warp-unlimited-okteto
    environment:
      - WARP_CLIENT_ID='a3d539df-91fc-4ee3-91ff-c49dca629022'
      - SEND_LOG=False

    ports:
      - 8080:8080
    restart: unless-stopped
